### PR TITLE
Updated German Translations

### PR DESCRIPTION
**Pull request by rvan-dev**
I added the translations for the new feature and fixed some of the old ones that were incorrect/not fiting

### CODE REVIEW

**Comment by jaatroko** [comment]
Looks mainly good, but there are some fixes needed:

You should credit yourself in the `translator` key. There are only so many ways technical non-fiction text can be translated, and the *creative* work involved is close to nonexistent, so I see no reason to keep previous translators in the credits: the current translator will "own" the translation as a whole.

Though I do not speak German, I did read through the diff and noticed the following:
* In `_currentlyOpenDescription_html`: 1) "Subdomain" vs. "Domänenübergreifend", is "Subdomain" correct here? 2) "das das Fragment verändert", "das" repeated erroneusly, or should it be like this? 3) "Mit anderen Worten:" is repeated.
* `__newsTitle` is untranslated(?)
* There are inconsistencies in word capitalization (in the previous translation), e.g. with "Format" and "Namen". You may want to check for these.

**Comment by rvan-tgm** [comment]
Everything should be fixed now, sorry for being so sloppy ^^, "das das" was a typo and "Mit anderen worten" was probably me just taking to long to think about how to write the sentence and then starting it from the beginning again. Subdomain is indeed correct and News would have been fitting (also used in the german language) but I still translated it now. With the capitalizations I fixed those that I found. So it should be ready to merge now

**Comment by jaatroko** [comment]
You changed the descriptions `__customWeekdayNames_label` and `__customMonthNames_label`: those input fields are comma-separated lists of weekday and month names to be used in formatting dates, are you certain "Format für Wochentage|Monate" is appropriate here? I mean, in English "Weekday names" and "Month names" are definitely more correct over anything with "format": format implies getting to define some *form* or structure instead of just a list of values. Or does the word have a different/wider meaning in German?

**Comment by rvan-tgm** [comment]
Well I checked how it looked in the settings page on the english version and in my understanding you put the format of the days (Mon,Tue, instead of Monday,Tuesday and the same for the months Jan,Feb instead of January and February) in my understanding that would be the format for how those 2 things are getting displayed

**Comment by jaatroko** [comment]
Ah, when you put it like that, I can see how you could use format in this context, making a distinction between what a weekday/month name *is* and how you want it to *appear* (you can, of course, use the full names in the lists). My concern is that using "format" could imply wider choice to the user than just naming things, but I guess the default lists will make it sufficiently clear what is expected in the fields, so I think your changes are ok.

**Comment by jaatroko** [comment]
Merged, will upload to AMO shortly. Thanks for your contribution. I will mark you in my notes as the German translator for future translation needs.

**Pull request merged**
